=== florindofp/LDM-Tests-and-Exercises/ldm-20-21/2021-01-13/ejemplo.dtd
<!ELEMENT stock(articulo*)>
<!ELEMENT articulo(nombre,antiguedad,precio)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT antiguedad(#PCDATA)>
<!ELEMENT precio(#PCDATA)>

=== florindofp/LDM-Tests-and-Exercises/ldm-20-21/2021-01-13/ejemplo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE stock SYSTEM "ejemplo.dtd">
<stock>
    <articulo>
        <nombre>Moto</nombre>
        <antiguedad unidad="meses">30</antiguedad>
        <precio unidad="euros">3000</precio>
    </articulo>
    <articulo>
        <nombre>Coche</nombre>
        <antiguedad unidad="meses">30</antiguedad>
        <precio unidad="euros">3000</precio>
    </articulo>
</stock>
