=== florindofp/LDM-Tests-and-Exercises/ldm-20-21/2021-01-28/sms.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.w3schools.com"
    xmlns="https://www.w3schools.com"
    elementFormDefault="qualified">

	<xs:element name="BDsms">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sms" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="telefono" type="xs:string"/>
							<xs:element name="fecha" type="xs:date"/>
							<xs:element name="hora" type="xs:time"/>
							<xs:element name="mensaje" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== florindofp/LDM-Tests-and-Exercises/ldm-20-21/2021-01-28/sms.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDsms
    xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com/xml sms.xsd">
  <sms>
    <telefono>65265271</telefono>
    <fecha>01/07/2020</fecha>
    <hora>20:21</hora>
    <mensaje>Hello, How are you going?</mensaje>
  </sms>
  <sms>
    <telefono>65265281</telefono>
    <fecha>11/07/2020</fecha>
    <hora>19:21</hora>
    <mensaje>Hello, I am working at home</mensaje>
  </sms>
  <sms>
    <telefono>65235271</telefono>
    <fecha>12/07/2020</fecha>
    <hora>19:21</hora>
    <mensaje>See you later</mensaje>
  </sms>
  <sms>
    <telefono>62265271</telefono>
    <fecha>19/07/2020</fecha>
    <hora>10:21</hora>
    <mensaje>Pace off</mensaje>
  </sms>
</BDsms>
